version: '3.8'

services:
  frontend:
    build:
      context: ./FrontendWebApplication
      dockerfile: Dockerfile
      args:
        ENV: docker
    ports:
      - "4200:4200"
    depends_on:
      - remote
    networks:
      - microfrontend-network

  remote:
    build:
      context: ./RemoteFrontendWebApplication
      dockerfile: Dockerfile
      args:
        ENV: docker
    ports:
      - "4201:4201"
    networks:
      - microfrontend-network

networks:
  microfrontend-network:
    driver: bridge