version: '3.8'

services:
  frontend:
    build:
      context: ./FrontendWebApplication
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - remote

  remote:
    build:
      context: ./RemoteFrontendWebApplication
      dockerfile: Dockerfile
    ports:
      - "4201:80"