version: '3.8'

services:
  frontend:
    build:
      context: ./FrontendWebApplication
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - remote
    environment:
      REMOTE_ENTRY_URL: "http://remote:4201/remoteEntry.json"
    networks:
      - microfrontend-network

  remote:
    build:
      context: ./RemoteFrontendWebApplication
      dockerfile: Dockerfile
    ports:
      - "4201:4201"
    networks:
      - microfrontend-network

networks:
  microfrontend-network:
    driver: bridge